### ISSUE TITLE
Default box values that can be applied to boxes of the same type

### ISSUE THREAD

**Issue by bobthebutcher** [bobthebutcher/vagrant-topology-builder#17]
Add a mechanism to apply box default values to all boxes of the same type.

```yaml
arista/veos:
  vagrant_box:
    version: "4.20.1F"
  insert_ssh_key: False
  synced_folder: 
    disabled: True
  provider_config:
    nic_adapter_count: 2
    disk_bus: "ide"
    cpus: 2
    memory: 2048
```
